name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install runtime dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then
              python -m pip install -r requirements.txt
            else
              echo "No requirements.txt"
            fi
          shell: bash

      - name: Install dev dependencies (optional)
        if: hashFiles('requirements-dev.txt') != ''
        run: python -m pip install -r requirements-dev.txt

      - name: Run tests (if present)
        if: hashFiles('tests/**') != ''
        run: pytest -q
