name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create artifact directory
        run: mkdir -p dist

      - name: Copy files
        run: |
          cp Basic_Wallet_Scanner.py dist/
          cp -r pywallet dist/pywallet
          cp README.md dist/
          cp requirements.txt dist/
          if [ -f requirements-dev.txt ]; then cp requirements-dev.txt dist/; fi
          cp LICENSE dist/

      - name: Package zip
        run: |
          cd dist
          zip -r crypto-wallet-explorer.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/crypto-wallet-explorer.zip